### ISSUE TITLE
sanbox test?

### ISSUE THREAD

**Issue by sullivanhikaru** [HighRiskShop/WooCommerce-Instant-Payment-Gateway#1]
Hello, I want to use the "Instant Approval Payment Gateway with Instant Payouts" plugin, but I am in China. Is there a sanbox test? I tried to pay directly but it said that China cannot pay with cryptocurrency. How can I test it?

**Comment by ghost** [comment]
> Hello, I want to use the "Instant Approval Payment Gateway with Instant Payouts" plugin, but I am in China. Is there a sanbox test? I tried to pay directly but it said that China cannot pay with cryptocurrency. How can I test it?

Hello
This plugin is free and the API is open. You don't need to purchase anything. If you want to test the final checkout process then you can use the payment link generator: https://www.highriskshop.com/payment-link/

For more information: https://www.highriskshop.com/instant-payment-gateway/

Contact us on Telegram if you want to discuss more.

Thank you
